import type { Achievement } from "@/types"

export const ACHIEVEMENTS: Achievement[] = [
  {
    slug: "first-frame",
    name: "First Frame",
    description: "Complete your first photography lesson",
    icon: "📷",
    xpReward: 0,
    rarity: "common",
  },
  {
    slug: "colour-theory",
    name: "Colour Theory",
    description: "Complete the colour theory lesson",
    icon: "🎨",
    xpReward: 0,
    rarity: "common",
  },
  {
    slug: "night-owl",
    name: "Night Owl",
    description: "Complete the Midnight Aesthetics path",
    icon: "🌙",
    xpReward: 50,
    rarity: "rare",
  },
  {
    slug: "chain-reaction",
    name: "Chain Reaction",
    description: "Complete your first photographer discovery chain",
    icon: "🔗",
    xpReward: 75,
    rarity: "rare",
  },
  {
    slug: "bibliophile",
    name: "Bibliophile",
    description: "Save 10 references to your moodboard",
    icon: "📚",
    xpReward: 25,
    rarity: "common",
  },
  {
    slug: "reflective",
    name: "Reflective",
    description: "Write 5 journal entries",
    icon: "✍️",
    xpReward: 25,
    rarity: "common",
  },
  {
    slug: "art-historian",
    name: "Art Historian",
    description: "Complete the Art History path",
    icon: "🏛️",
    xpReward: 100,
    rarity: "rare",
  },
  {
    slug: "cinephile",
    name: "Cinephile",
    description: "Complete the Film & Cinematography path",
    icon: "🎬",
    xpReward: 100,
    rarity: "rare",
  },
  {
    slug: "concept-creator",
    name: "Concept Creator",
    description: "Complete the Creative Direction path",
    icon: "💡",
    xpReward: 100,
    rarity: "rare",
  },
  {
    slug: "visual-thinker",
    name: "Visual Thinker",
    description: "Reach Level 5",
    icon: "👁️",
    xpReward: 200,
    rarity: "epic",
  },
  {
    slug: "visionary",
    name: "Visionary",
    description: "Reach Level 10",
    icon: "🏆",
    xpReward: 500,
    rarity: "legendary",
  },
  {
    slug: "on-fire",
    name: "On Fire",
    description: "Maintain a 7-day streak",
    icon: "🔥",
    xpReward: 100,
    rarity: "rare",
  },
  {
    slug: "dedicated",
    name: "Dedicated",
    description: "Maintain a 30-day streak",
    icon: "💎",
    xpReward: 300,
    rarity: "epic",
  },
  {
    slug: "glossed",
    name: "Glossed",
    description: "Master all 20 glossary terms",
    icon: "📖",
    xpReward: 150,
    rarity: "rare",
  },
  {
    slug: "culture-explorer",
    name: "Culture Explorer",
    description: "Complete 3 different learning paths",
    icon: "🌍",
    xpReward: 200,
    rarity: "epic",
  },
  {
    slug: "marksman",
    name: "Marksman",
    description: "Perfect score on 5 quizzes in a row",
    icon: "🎯",
    xpReward: 150,
    rarity: "epic",
  },
  {
    slug: "tillmans-fan",
    name: "Tillmans Fan",
    description: "Complete the Wolfgang Tillmans path",
    icon: "🕊️",
    xpReward: 100,
    rarity: "rare",
  },
  {
    slug: "lindbergh-legacy",
    name: "Lindbergh Legacy",
    description: "Complete the Peter Lindbergh path",
    icon: "🌹",
    xpReward: 100,
    rarity: "rare",
  },
  {
    slug: "dream-state",
    name: "Dream State",
    description: "Complete the Dreamlike & Surrealist paths",
    icon: "🌌",
    xpReward: 150,
    rarity: "epic",
  },
  {
    slug: "curator",
    name: "Curator",
    description: "Save and organise 5 moodboard collections",
    icon: "👑",
    xpReward: 100,
    rarity: "rare",
  },
]

export function getAchievementBySlug(slug: string): Achievement | undefined {
  return ACHIEVEMENTS.find((a) => a.slug === slug)
}
