import type { Photographer, DiscoveryChain } from "@/types"

export const PHOTOGRAPHERS: Photographer[] = [
  {
    id: "wolfgang-tillmans",
    name: "Wolfgang Tillmans",
    born: "1968",
    nationality: "German",
    bio: "Turner Prize-winning photographer whose work spans fashion, documentary, portraiture, and abstract darkroom studies. Defined a generation of visual culture through i-D, The Face, and major gallery exhibitions.",
    styleDescription:
      "Documentary intimacy, available light, anti-hierarchical subject matter, radical installation practice.",
    tags: ["documentary", "fashion", "contemporary", "abstract", "club-culture"],
    accentColor: "#c4a4e8",
    courseId: "wolfgang-tillmans",
    discoveryChain: ["nan-goldin", "juergen-teller"],
    influences: ["nan-goldin", "joseph-beuys"],
  },
  {
    id: "nan-goldin",
    name: "Nan Goldin",
    born: "1953",
    nationality: "American",
    bio: "Documentary photographer whose seminal work 'The Ballad of Sexual Dependency' captured New York's underground scene in the 70s and 80s. Her diary-form photography redefined intimacy in the medium.",
    styleDescription:
      "Raw personal documentary, flash photography, intimate portraiture, diary-form narrative.",
    tags: ["documentary", "diary", "portrait", "underground", "flash"],
    accentColor: "#e87777",
    courseId: "nan-goldin",
    discoveryChain: ["juergen-teller", "ryan-mcginley"],
    influences: ["larry-clark", "diane-arbus"],
  },
  {
    id: "nick-knight",
    name: "Nick Knight",
    born: "1958",
    nationality: "British",
    bio: "Pioneer of digital and experimental fashion photography. Founded SHOWstudio, revolutionising how fashion imagery is made and consumed. Known for technically innovative, often disturbing beauty.",
    styleDescription:
      "Digital experimentation, conceptual fashion, high-tech aesthetic, colour as concept.",
    tags: ["fashion", "digital", "experimental", "conceptual", "editorial"],
    accentColor: "#47b8e8",
    courseId: "nick-knight",
    discoveryChain: ["solve-sundsbo", "mert-marcus"],
    influences: ["alexander-mcqueen", "yohji-yamamoto"],
  },
  {
    id: "tim-walker",
    name: "Tim Walker",
    born: "1970",
    nationality: "British",
    bio: "British fashion photographer known for elaborate, dreamlike, fairy-tale imagery. His elaborate sets and surrealist scenarios have defined a certain strand of British fashion photography.",
    styleDescription:
      "Surrealist fantasy, elaborate sets, hyper-saturated colour, narrative storytelling.",
    tags: ["fashion", "surrealist", "fantasy", "editorial", "storytelling"],
    accentColor: "#e8a447",
    courseId: "tim-walker",
    discoveryChain: ["annie-leibovitz", "david-lachapelle"],
    influences: ["lewis-carroll", "salvador-dali", "richard-avedon"],
  },
  {
    id: "peter-lindbergh",
    name: "Peter Lindbergh",
    born: "1944",
    nationality: "German",
    bio: "German-French photographer who transformed fashion photography by stripping away artifice — natural light, minimal makeup, women as themselves. His 1990 Vogue cover launched the supermodel era.",
    styleDescription:
      "Black and white, natural light, emotional truth, documentary fashion, minimal retouching.",
    tags: ["fashion", "documentary", "black-and-white", "natural", "portrait"],
    accentColor: "#a0a0a0",
    courseId: "peter-lindbergh",
    discoveryChain: ["herb-ritts", "richard-avedon"],
    influences: ["wim-wenders", "ingmar-bergman"],
  },
  {
    id: "aidan-zamiri",
    name: "Aidan Zamiri",
    born: "1991",
    nationality: "British",
    bio: "Contemporary British photographer known for a naturalistic, intimate approach to fashion and editorial photography. His work has appeared in AnOther, Dazed, and for major fashion houses.",
    styleDescription:
      "Naturalistic, intimate, contemporary editorial, honest portraiture, nocturnal aesthetics.",
    tags: ["contemporary", "editorial", "naturalistic", "fashion", "portrait"],
    accentColor: "#7ba88c",
    courseId: "aidan-zamiri",
    discoveryChain: ["rafael-pavarotti", "jordan-hemingway"],
    influences: ["wolfgang-tillmans", "juergen-teller"],
  },
  {
    id: "annie-leibovitz",
    name: "Annie Leibovitz",
    born: "1949",
    nationality: "American",
    bio: "America's most celebrated portrait photographer. Staff photographer for Rolling Stone, then Vanity Fair — creator of iconic cultural portraits for over five decades.",
    styleDescription:
      "Theatrical portraiture, strong narrative concept, studio and location work, celebrity subjects.",
    tags: ["portrait", "celebrity", "editorial", "narrative", "american"],
    accentColor: "#e8b847",
    courseId: "annie-leibovitz",
    discoveryChain: ["tim-walker", "david-lachapelle"],
    influences: ["richard-avedon", "susan-sontag"],
  },
  {
    id: "richard-avedon",
    name: "Richard Avedon",
    born: "1923",
    nationality: "American",
    bio: "Considered one of the most influential American photographers of the 20th century. Transformed fashion and portrait photography with his stark white backgrounds and psychological intensity.",
    styleDescription:
      "Stark white background, psychological portraiture, fashion energy, movement.",
    tags: ["portrait", "fashion", "american", "20th-century", "stark"],
    accentColor: "#e8e8e8",
    courseId: "richard-avedon",
    discoveryChain: ["irving-penn", "peter-lindbergh"],
    influences: ["martin-munkacsi", "alexey-brodovitch"],
  },
  {
    id: "helmut-newton",
    name: "Helmut Newton",
    born: "1920",
    nationality: "German-Australian",
    bio: "Provocateur and fashion photographer who brought sexuality, power, and transgression into Vogue and other high-fashion publications. His work remains contentious and compelling.",
    styleDescription:
      "Sexuality, power dynamics, chiaroscuro, black and white, luxury settings.",
    tags: ["fashion", "provocateur", "black-and-white", "luxury", "portrait"],
    accentColor: "#2a2a2a",
    courseId: "helmut-newton",
    discoveryChain: ["steven-meisel", "mario-testino"],
    influences: ["george-hoyningen-huene", "horst-p-horst"],
  },
  {
    id: "irving-penn",
    name: "Irving Penn",
    born: "1917",
    nationality: "American",
    bio: "Master of studio photography. Penn's meticulous, formally rigorous images — whether fashion, portraiture, or still life — are among the most refined in the medium's history.",
    styleDescription: "Studio precision, formal composition, restrained elegance, still life.",
    tags: ["studio", "portrait", "still-life", "fashion", "formal"],
    accentColor: "#d4c5b0",
    courseId: "irving-penn",
    discoveryChain: ["richard-avedon", "paolo-roversi"],
    influences: ["alexey-brodovitch", "walker-evans"],
  },
  {
    id: "juergen-teller",
    name: "Juergen Teller",
    born: "1964",
    nationality: "German",
    bio: "Anti-fashion fashion photographer. Teller's raw, deliberately 'bad' aesthetic — overexposed flash, unflattering angles, ugly-beautiful subjects — upended the conventions of the industry.",
    styleDescription:
      "Raw flash photography, anti-aesthetic, confessional, deliberately unflattering.",
    tags: ["fashion", "anti-aesthetic", "flash", "confessional", "contemporary"],
    accentColor: "#f0e060",
    courseId: "juergen-teller",
    discoveryChain: ["wolfgang-tillmans", "nan-goldin"],
    influences: ["nan-goldin", "larry-clark"],
  },
  {
    id: "paolo-roversi",
    name: "Paolo Roversi",
    born: "1947",
    nationality: "Italian",
    bio: "Italian photographer celebrated for ethereal, painterly images made on large-format Polaroid. His work combines technical mastery with an almost mystical approach to beauty.",
    styleDescription:
      "Large-format Polaroid, soft focus, painterly light, ethereal beauty, timeless.",
    tags: ["fashion", "polaroid", "ethereal", "painterly", "portrait"],
    accentColor: "#b8c4e8",
    courseId: "paolo-roversi",
    discoveryChain: ["irving-penn", "peter-lindbergh"],
    influences: ["edward-steichen", "sarah-moon"],
  },
  {
    id: "harley-weir",
    name: "Harley Weir",
    born: "1988",
    nationality: "British",
    bio: "Contemporary British photographer known for intimate, often sensual images that merge fashion with a raw personal aesthetic. Her work appears in Vogue, AnOther, and for major houses.",
    styleDescription: "Intimate, sensual, contemporary, raw, close-range portraiture.",
    tags: ["contemporary", "fashion", "intimate", "british", "portrait"],
    accentColor: "#e8b4c4",
    courseId: "harley-weir",
    discoveryChain: ["aidan-zamiri", "wolfgang-tillmans"],
    influences: ["nan-goldin", "daido-moriyama"],
  },
  {
    id: "steven-meisel",
    name: "Steven Meisel",
    born: "1954",
    nationality: "American",
    bio: "The most influential fashion photographer working today. Every Vogue Italia cover for decades, the discoverer of most major supermodels, creator of some of the most culturally significant fashion images ever made.",
    styleDescription:
      "High-fashion glossy, chameleon aesthetic, narrative editorials, trend-defining.",
    tags: ["fashion", "editorial", "vogue", "american", "trend-setting"],
    accentColor: "#c8a8d8",
    courseId: "steven-meisel",
    discoveryChain: ["nick-knight", "bruce-weber"],
    influences: ["richard-avedon", "guy-bourdin"],
  },
  {
    id: "herb-ritts",
    name: "Herb Ritts",
    born: "1952",
    nationality: "American",
    bio: "Californian photographer whose sun-drenched, sculptural black-and-white images of the human body defined an era of fashion and celebrity photography in the 1980s and 90s.",
    styleDescription:
      "Black and white, sculptural bodies, California light, classic elegance, clean.",
    tags: ["portrait", "fashion", "black-and-white", "american", "sculptural"],
    accentColor: "#c8c8b0",
    courseId: "herb-ritts",
    discoveryChain: ["peter-lindbergh", "richard-avedon"],
    influences: ["george-hoyningen-huene", "edward-weston"],
  },
  {
    id: "solve-sundsbo",
    name: "Sølve Sundsbø",
    born: "1970",
    nationality: "Norwegian",
    bio: "Norwegian-born, London-based photographer known for technically sophisticated, digitally enhanced fashion imagery. Closely associated with Nick Knight and SHOWstudio.",
    styleDescription:
      "Digital enhancement, sculptural bodies, technical innovation, high-fashion concept.",
    tags: ["fashion", "digital", "contemporary", "technical", "conceptual"],
    accentColor: "#78c8e8",
    courseId: "solve-sundsbo",
    discoveryChain: ["nick-knight", "mert-marcus"],
    influences: ["nick-knight", "helmut-newton"],
  },
  {
    id: "david-lachapelle",
    name: "David LaChapelle",
    born: "1963",
    nationality: "American",
    bio: "American photographer famous for hyper-saturated, surrealist, often religious or apocalyptic imagery. His work is maximalist, kitsch, profound, and deeply American.",
    styleDescription:
      "Hyper-saturated, maximalist, surrealist, religious iconography, American kitsch.",
    tags: ["fashion", "surrealist", "maximalist", "american", "celebrity"],
    accentColor: "#e84747",
    courseId: "david-lachapelle",
    discoveryChain: ["tim-walker", "annie-leibovitz"],
    influences: ["andy-warhol", "salvador-dali"],
  },
  {
    id: "martin-parr",
    name: "Martin Parr",
    born: "1952",
    nationality: "British",
    bio: "British documentary and street photographer known for his satirical, vivid, often humorous documentation of British life and global consumer culture. Magnum Photos member.",
    styleDescription: "Vivid colour, flash, satire, documentary, British culture, close-range.",
    tags: ["documentary", "street", "british", "colour", "satire"],
    accentColor: "#e87847",
    courseId: "martin-parr",
    discoveryChain: ["nan-goldin", "juergen-teller"],
    influences: ["tony-ray-jones", "eggleston"],
  },
]

export const PHOTOGRAPHER_INDEX: Record<string, Photographer> = Object.fromEntries(
  PHOTOGRAPHERS.map((p) => [p.id, p])
)

export const DISCOVERY_CHAINS: DiscoveryChain[] = [
  {
    id: "chain-tillmans",
    name: "The Intimate Eye",
    photographers: ["wolfgang-tillmans", "nan-goldin", "juergen-teller", "harley-weir"],
    description:
      "A lineage of photographers who prioritised intimacy, community, and documentary truth over glamour.",
  },
  {
    id: "chain-lindbergh",
    name: "The Human Truth",
    photographers: ["peter-lindbergh", "herb-ritts", "richard-avedon", "irving-penn", "paolo-roversi"],
    description:
      "Photographers who found beauty in authenticity — natural light, honest subjects, formal elegance.",
  },
  {
    id: "chain-walker",
    name: "The Dreammakers",
    photographers: ["tim-walker", "annie-leibovitz", "david-lachapelle"],
    description:
      "Storytellers who created entire worlds within their frames — fantasy, narrative, and theatrical vision.",
  },
  {
    id: "chain-knight",
    name: "The Experimentalists",
    photographers: ["nick-knight", "solve-sundsbo", "steven-meisel"],
    description:
      "Photographers who pushed fashion imagery into new technical and conceptual territory.",
  },
  {
    id: "chain-zamiri",
    name: "The New Wave",
    photographers: ["aidan-zamiri", "harley-weir", "wolfgang-tillmans"],
    description:
      "Contemporary photographers redefining what fashion and editorial photography looks like today.",
  },
]

export function getPhotographer(id: string): Photographer | undefined {
  return PHOTOGRAPHER_INDEX[id]
}
